import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val approvaltests: String = "com.approvaltests:approvaltests:_"

    const val jackson_databind: String = "com.fasterxml.jackson.core:jackson-databind"

    const val jackson_module_parameter_names: String =
            "com.fasterxml.jackson.module:jackson-module-parameter-names"

    const val jackson_bom: String = "com.fasterxml.jackson:jackson-bom:_"

    const val gson: String = "com.google.code.gson:gson:_"

    const val moshi: String = "com.squareup.moshi:moshi:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val vavr: String = "io.vavr:vavr:_"

    const val assertj_core: String = "org.assertj:assertj-core:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine"

    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params"

    const val junit_bom: String = "org.junit:junit-bom:_"

    const val jsonassert: String = "org.skyscreamer:jsonassert:_"
}
